name: Deploy reform-sss-resizer

on:
  push:
    tags:
      - "**"

jobs:
  build-deploy:
    name: Build resizer & Build image & Deploy Scaleway
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"

      - name: Print go version
        run: go version

      - name: Build resizer
        run: make build

      - name: Login Scaleway
        run: docker login rg.fr-par.scw.cloud/platinmarket -u nologin -p ${{ secrets.SCALEWAY_SECRET }}

      - name: Build reform-sss-resizer container
        run: docker build . --file Dockerfile --tag "rg.fr-par.scw.cloud/platinmarket/reform-sss-resizer:${{ github.sha }}" --tag "rg.fr-par.scw.cloud/platinmarket/reform-sss-resizer:latest"

      - name: Push reform-sss-resizer to scaleway container repository
        run: docker push rg.fr-par.scw.cloud/platinmarket/reform-sss-resizer --all-tags
